/**
 * ISO 3166-1 alpha-2 country codes and IOC NOC 3-letter codes.
 * Source: ISO 3166 Maintenance Agency / Wikipedia IOC country codes list.
 *
 * v1.0 note: these will be replaced by a live lookup against Common Codes.
 */

export const COUNTRY_CODES: { code: string; name: string }[] = [
  { code: "AD", name: "Andorra" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "AF", name: "Afghanistan" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AI", name: "Anguilla" },
  { code: "AL", name: "Albania" },
  { code: "AM", name: "Armenia" },
  { code: "AO", name: "Angola" },
  { code: "AQ", name: "Antarctica" },
  { code: "AR", name: "Argentina" },
  { code: "AS", name: "American Samoa" },
  { code: "AT", name: "Austria" },
  { code: "AU", name: "Australia" },
  { code: "AW", name: "Aruba" },
  { code: "AX", name: "Åland Islands" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BB", name: "Barbados" },
  { code: "BD", name: "Bangladesh" },
  { code: "BE", name: "Belgium" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BG", name: "Bulgaria" },
  { code: "BH", name: "Bahrain" },
  { code: "BI", name: "Burundi" },
  { code: "BJ", name: "Benin" },
  { code: "BL", name: "Saint Barthélemy" },
  { code: "BM", name: "Bermuda" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BO", name: "Bolivia" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "BR", name: "Brazil" },
  { code: "BS", name: "Bahamas" },
  { code: "BT", name: "Bhutan" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BW", name: "Botswana" },
  { code: "BY", name: "Belarus" },
  { code: "BZ", name: "Belize" },
  { code: "CA", name: "Canada" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CD", name: "Congo, Democratic Republic of the" },
  { code: "CF", name: "Central African Republic" },
  { code: "CG", name: "Congo" },
  { code: "CH", name: "Switzerland" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "CK", name: "Cook Islands" },
  { code: "CL", name: "Chile" },
  { code: "CM", name: "Cameroon" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "CV", name: "Cabo Verde" },
  { code: "CW", name: "Curaçao" },
  { code: "CX", name: "Christmas Island" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "DE", name: "Germany" },
  { code: "DJ", name: "Djibouti" },
  { code: "DK", name: "Denmark" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "DZ", name: "Algeria" },
  { code: "EC", name: "Ecuador" },
  { code: "EE", name: "Estonia" },
  { code: "EG", name: "Egypt" },
  { code: "EH", name: "Western Sahara" },
  { code: "ER", name: "Eritrea" },
  { code: "ES", name: "Spain" },
  { code: "ET", name: "Ethiopia" },
  { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fiji" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FM", name: "Micronesia, Federated States of" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GB", name: "United Kingdom" },
  { code: "GD", name: "Grenada" },
  { code: "GE", name: "Georgia" },
  { code: "GF", name: "French Guiana" },
  { code: "GG", name: "Guernsey" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GL", name: "Greenland" },
  { code: "GM", name: "Gambia" },
  { code: "GN", name: "Guinea" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "GR", name: "Greece" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "GT", name: "Guatemala" },
  { code: "GU", name: "Guam" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HK", name: "Hong Kong" },
  { code: "HM", name: "Heard Island and McDonald Islands" },
  { code: "HN", name: "Honduras" },
  { code: "HR", name: "Croatia" },
  { code: "HT", name: "Haiti" },
  { code: "HU", name: "Hungary" },
  { code: "ID", name: "Indonesia" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IM", name: "Isle of Man" },
  { code: "IN", name: "India" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "IQ", name: "Iraq" },
  { code: "IR", name: "Iran" },
  { code: "IS", name: "Iceland" },
  { code: "IT", name: "Italy" },
  { code: "JE", name: "Jersey" },
  { code: "JM", name: "Jamaica" },
  { code: "JO", name: "Jordan" },
  { code: "JP", name: "Japan" },
  { code: "KE", name: "Kenya" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "KH", name: "Cambodia" },
  { code: "KI", name: "Kiribati" },
  { code: "KM", name: "Comoros" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "KP", name: "Korea, Democratic People's Republic of" },
  { code: "KR", name: "Korea, Republic of" },
  { code: "KW", name: "Kuwait" },
  { code: "KY", name: "Cayman Islands" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "LA", name: "Lao People's Democratic Republic" },
  { code: "LB", name: "Lebanon" },
  { code: "LC", name: "Saint Lucia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka" },
  { code: "LR", name: "Liberia" },
  { code: "LS", name: "Lesotho" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "LV", name: "Latvia" },
  { code: "LY", name: "Libya" },
  { code: "MA", name: "Morocco" },
  { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldova" },
  { code: "ME", name: "Montenegro" },
  { code: "MF", name: "Saint Martin (French part)" },
  { code: "MG", name: "Madagascar" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MK", name: "North Macedonia" },
  { code: "ML", name: "Mali" },
  { code: "MM", name: "Myanmar" },
  { code: "MN", name: "Mongolia" },
  { code: "MO", name: "Macao" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MS", name: "Montserrat" },
  { code: "MT", name: "Malta" },
  { code: "MU", name: "Mauritius" },
  { code: "MV", name: "Maldives" },
  { code: "MW", name: "Malawi" },
  { code: "MX", name: "Mexico" },
  { code: "MY", name: "Malaysia" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibia" },
  { code: "NC", name: "New Caledonia" },
  { code: "NE", name: "Niger" },
  { code: "NF", name: "Norfolk Island" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nicaragua" },
  { code: "NL", name: "Netherlands" },
  { code: "NO", name: "Norway" },
  { code: "NP", name: "Nepal" },
  { code: "NR", name: "Nauru" },
  { code: "NU", name: "Niue" },
  { code: "NZ", name: "New Zealand" },
  { code: "OM", name: "Oman" },
  { code: "PA", name: "Panama" },
  { code: "PE", name: "Peru" },
  { code: "PF", name: "French Polynesia" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PH", name: "Philippines" },
  { code: "PK", name: "Pakistan" },
  { code: "PL", name: "Poland" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "PN", name: "Pitcairn" },
  { code: "PR", name: "Puerto Rico" },
  { code: "PS", name: "Palestine" },
  { code: "PT", name: "Portugal" },
  { code: "PW", name: "Palau" },
  { code: "PY", name: "Paraguay" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RS", name: "Serbia" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Rwanda" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SC", name: "Seychelles" },
  { code: "SD", name: "Sudan" },
  { code: "SE", name: "Sweden" },
  { code: "SG", name: "Singapore" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "SI", name: "Slovenia" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SK", name: "Slovakia" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SM", name: "San Marino" },
  { code: "SN", name: "Senegal" },
  { code: "SO", name: "Somalia" },
  { code: "SR", name: "Suriname" },
  { code: "SS", name: "South Sudan" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SV", name: "El Salvador" },
  { code: "SX", name: "Sint Maarten (Dutch part)" },
  { code: "SY", name: "Syria" },
  { code: "SZ", name: "Eswatini" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TD", name: "Chad" },
  { code: "TF", name: "French Southern Territories" },
  { code: "TG", name: "Togo" },
  { code: "TH", name: "Thailand" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TK", name: "Tokelau" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TN", name: "Tunisia" },
  { code: "TO", name: "Tonga" },
  { code: "TR", name: "Türkiye" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TV", name: "Tuvalu" },
  { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" },
  { code: "UA", name: "Ukraine" },
  { code: "UG", name: "Uganda" },
  { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "US", name: "United States of America" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VA", name: "Holy See" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "VE", name: "Venezuela" },
  { code: "VG", name: "Virgin Islands (British)" },
  { code: "VI", name: "Virgin Islands (U.S.)" },
  { code: "VN", name: "Viet Nam" },
  { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "WS", name: "Samoa" },
  { code: "YE", name: "Yemen" },
  { code: "YT", name: "Mayotte" },
  { code: "ZA", name: "South Africa" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

// IOC NOC codes — these differ meaningfully from ISO alpha-3
// (e.g. GER not DEU, SUI not CHE, GBR = Great Britain, TPE = Chinese Taipei)
export const NOC_CODES: { code: string; name: string }[] = [
  { code: "AFG", name: "Afghanistan" },
  { code: "ALB", name: "Albania" },
  { code: "ALG", name: "Algeria" },
  { code: "AND", name: "Andorra" },
  { code: "ANG", name: "Angola" },
  { code: "ANT", name: "Antigua and Barbuda" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Armenia" },
  { code: "ARU", name: "Aruba" },
  { code: "ASA", name: "American Samoa" },
  { code: "AUS", name: "Australia" },
  { code: "AUT", name: "Austria" },
  { code: "AZE", name: "Azerbaijan" },
  { code: "BAH", name: "Bahamas" },
  { code: "BAN", name: "Bangladesh" },
  { code: "BAR", name: "Barbados" },
  { code: "BDI", name: "Burundi" },
  { code: "BEL", name: "Belgium" },
  { code: "BEN", name: "Benin" },
  { code: "BER", name: "Bermuda" },
  { code: "BHU", name: "Bhutan" },
  { code: "BIH", name: "Bosnia and Herzegovina" },
  { code: "BIZ", name: "Belize" },
  { code: "BLR", name: "Belarus" },
  { code: "BOL", name: "Bolivia" },
  { code: "BOT", name: "Botswana" },
  { code: "BRA", name: "Brazil" },
  { code: "BRN", name: "Bahrain" },
  { code: "BRU", name: "Brunei" },
  { code: "BUL", name: "Bulgaria" },
  { code: "BUR", name: "Burkina Faso" },
  { code: "CAF", name: "Central African Republic" },
  { code: "CAM", name: "Cambodia" },
  { code: "CAN", name: "Canada" },
  { code: "CAY", name: "Cayman Islands" },
  { code: "CGO", name: "Republic of the Congo" },
  { code: "CHA", name: "Chad" },
  { code: "CHI", name: "Chile" },
  { code: "CHN", name: "China" },
  { code: "CIV", name: "Ivory Coast" },
  { code: "CMR", name: "Cameroon" },
  { code: "COD", name: "Democratic Republic of the Congo" },
  { code: "COK", name: "Cook Islands" },
  { code: "COL", name: "Colombia" },
  { code: "COM", name: "Comoros" },
  { code: "CPV", name: "Cape Verde" },
  { code: "CRC", name: "Costa Rica" },
  { code: "CRO", name: "Croatia" },
  { code: "CUB", name: "Cuba" },
  { code: "CYP", name: "Cyprus" },
  { code: "CZE", name: "Czech Republic" },
  { code: "DEN", name: "Denmark" },
  { code: "DJI", name: "Djibouti" },
  { code: "DMA", name: "Dominica" },
  { code: "DOM", name: "Dominican Republic" },
  { code: "ECU", name: "Ecuador" },
  { code: "EGY", name: "Egypt" },
  { code: "ERI", name: "Eritrea" },
  { code: "ESA", name: "El Salvador" },
  { code: "ESP", name: "Spain" },
  { code: "EST", name: "Estonia" },
  { code: "ETH", name: "Ethiopia" },
  { code: "FIJ", name: "Fiji" },
  { code: "FIN", name: "Finland" },
  { code: "FRA", name: "France" },
  { code: "FSM", name: "Federated States of Micronesia" },
  { code: "GAB", name: "Gabon" },
  { code: "GAM", name: "The Gambia" },
  { code: "GBR", name: "Great Britain" },
  { code: "GBS", name: "Guinea-Bissau" },
  { code: "GEO", name: "Georgia" },
  { code: "GEQ", name: "Equatorial Guinea" },
  { code: "GER", name: "Germany" },
  { code: "GHA", name: "Ghana" },
  { code: "GRE", name: "Greece" },
  { code: "GRN", name: "Grenada" },
  { code: "GUA", name: "Guatemala" },
  { code: "GUI", name: "Guinea" },
  { code: "GUM", name: "Guam" },
  { code: "GUY", name: "Guyana" },
  { code: "HAI", name: "Haiti" },
  { code: "HKG", name: "Hong Kong" },
  { code: "HON", name: "Honduras" },
  { code: "HUN", name: "Hungary" },
  { code: "INA", name: "Indonesia" },
  { code: "IND", name: "India" },
  { code: "IRI", name: "Iran" },
  { code: "IRL", name: "Ireland" },
  { code: "IRQ", name: "Iraq" },
  { code: "ISL", name: "Iceland" },
  { code: "ISR", name: "Israel" },
  { code: "ISV", name: "Virgin Islands" },
  { code: "ITA", name: "Italy" },
  { code: "IVB", name: "British Virgin Islands" },
  { code: "JAM", name: "Jamaica" },
  { code: "JOR", name: "Jordan" },
  { code: "JPN", name: "Japan" },
  { code: "KAZ", name: "Kazakhstan" },
  { code: "KEN", name: "Kenya" },
  { code: "KGZ", name: "Kyrgyzstan" },
  { code: "KIR", name: "Kiribati" },
  { code: "KOR", name: "South Korea" },
  { code: "KOS", name: "Kosovo" },
  { code: "KSA", name: "Saudi Arabia" },
  { code: "KUW", name: "Kuwait" },
  { code: "LAO", name: "Laos" },
  { code: "LAT", name: "Latvia" },
  { code: "LBA", name: "Libya" },
  { code: "LBN", name: "Lebanon" },
  { code: "LBR", name: "Liberia" },
  { code: "LCA", name: "Saint Lucia" },
  { code: "LES", name: "Lesotho" },
  { code: "LIE", name: "Liechtenstein" },
  { code: "LTU", name: "Lithuania" },
  { code: "LUX", name: "Luxembourg" },
  { code: "MAD", name: "Madagascar" },
  { code: "MAR", name: "Morocco" },
  { code: "MAS", name: "Malaysia" },
  { code: "MAW", name: "Malawi" },
  { code: "MDA", name: "Moldova" },
  { code: "MDV", name: "Maldives" },
  { code: "MEX", name: "Mexico" },
  { code: "MGL", name: "Mongolia" },
  { code: "MHL", name: "Marshall Islands" },
  { code: "MKD", name: "North Macedonia" },
  { code: "MLI", name: "Mali" },
  { code: "MLT", name: "Malta" },
  { code: "MNE", name: "Montenegro" },
  { code: "MON", name: "Monaco" },
  { code: "MOZ", name: "Mozambique" },
  { code: "MRI", name: "Mauritius" },
  { code: "MTN", name: "Mauritania" },
  { code: "MYA", name: "Myanmar" },
  { code: "NAM", name: "Namibia" },
  { code: "NCA", name: "Nicaragua" },
  { code: "NED", name: "Netherlands" },
  { code: "NEP", name: "Nepal" },
  { code: "NGR", name: "Nigeria" },
  { code: "NIG", name: "Niger" },
  { code: "NOR", name: "Norway" },
  { code: "NRU", name: "Nauru" },
  { code: "NZL", name: "New Zealand" },
  { code: "OMA", name: "Oman" },
  { code: "PAK", name: "Pakistan" },
  { code: "PAN", name: "Panama" },
  { code: "PAR", name: "Paraguay" },
  { code: "PER", name: "Peru" },
  { code: "PHI", name: "Philippines" },
  { code: "PLE", name: "Palestine" },
  { code: "PLW", name: "Palau" },
  { code: "PNG", name: "Papua New Guinea" },
  { code: "POL", name: "Poland" },
  { code: "POR", name: "Portugal" },
  { code: "PRK", name: "North Korea" },
  { code: "PUR", name: "Puerto Rico" },
  { code: "QAT", name: "Qatar" },
  { code: "ROU", name: "Romania" },
  { code: "RSA", name: "South Africa" },
  { code: "RUS", name: "Russia" },
  { code: "RWA", name: "Rwanda" },
  { code: "SAM", name: "Samoa" },
  { code: "SEN", name: "Senegal" },
  { code: "SEY", name: "Seychelles" },
  { code: "SGP", name: "Singapore" },
  { code: "SKN", name: "Saint Kitts and Nevis" },
  { code: "SLE", name: "Sierra Leone" },
  { code: "SLO", name: "Slovenia" },
  { code: "SMR", name: "San Marino" },
  { code: "SOL", name: "Solomon Islands" },
  { code: "SOM", name: "Somalia" },
  { code: "SRB", name: "Serbia" },
  { code: "SRI", name: "Sri Lanka" },
  { code: "SSD", name: "South Sudan" },
  { code: "STP", name: "São Tomé and Príncipe" },
  { code: "SUD", name: "Sudan" },
  { code: "SUI", name: "Switzerland" },
  { code: "SUR", name: "Suriname" },
  { code: "SVK", name: "Slovakia" },
  { code: "SWE", name: "Sweden" },
  { code: "SWZ", name: "Eswatini" },
  { code: "SYR", name: "Syria" },
  { code: "TAN", name: "Tanzania" },
  { code: "TGA", name: "Tonga" },
  { code: "THA", name: "Thailand" },
  { code: "TJK", name: "Tajikistan" },
  { code: "TKM", name: "Turkmenistan" },
  { code: "TLS", name: "Timor-Leste" },
  { code: "TOG", name: "Togo" },
  { code: "TPE", name: "Chinese Taipei" },
  { code: "TTO", name: "Trinidad and Tobago" },
  { code: "TUN", name: "Tunisia" },
  { code: "TUR", name: "Turkey" },
  { code: "TUV", name: "Tuvalu" },
  { code: "UAE", name: "United Arab Emirates" },
  { code: "UGA", name: "Uganda" },
  { code: "UKR", name: "Ukraine" },
  { code: "URU", name: "Uruguay" },
  { code: "USA", name: "United States" },
  { code: "UZB", name: "Uzbekistan" },
  { code: "VAN", name: "Vanuatu" },
  { code: "VEN", name: "Venezuela" },
  { code: "VIE", name: "Vietnam" },
  { code: "VIN", name: "Saint Vincent and the Grenadines" },
  { code: "YEM", name: "Yemen" },
  { code: "ZAM", name: "Zambia" },
  { code: "ZIM", name: "Zimbabwe" },
];

export const COUNTRY_CODE_SET = new Set(COUNTRY_CODES.map((c) => c.code));
export const NOC_CODE_SET = new Set(NOC_CODES.map((n) => n.code));

/**
 * Maps ISO 3166-1 alpha-2 country codes to IOC NOC codes.
 * Most countries map 1:1. Edge cases (multiple NOCs per country,
 * non-standard IOC codes) may require manual override.
 */
export const COUNTRY_TO_NOC: Record<string, string> = {
  "AD": "AND", "AE": "UAE", "AF": "AFG", "AG": "ANT", "AL": "ALB",
  "AM": "ARM", "AO": "ANG", "AR": "ARG", "AT": "AUT", "AU": "AUS",
  "AZ": "AZE", "BA": "BIH", "BB": "BAR", "BD": "BAN", "BE": "BEL",
  "BF": "BUR", "BG": "BUL", "BH": "BRN", "BI": "BDI", "BJ": "BEN",
  "BN": "BRU", "BO": "BOL", "BR": "BRA", "BS": "BAH", "BT": "BHU",
  "BW": "BOT", "BY": "BLR", "BZ": "BIZ", "CA": "CAN", "CD": "COD",
  "CF": "CAF", "CG": "CGO", "CH": "SUI", "CI": "CIV", "CL": "CHI",
  "CM": "CMR", "CN": "CHN", "CO": "COL", "CR": "CRC", "CU": "CUB",
  "CV": "CPV", "CY": "CYP", "CZ": "CZE", "DE": "GER", "DJ": "DJI",
  "DK": "DEN", "DM": "DMA", "DO": "DOM", "DZ": "ALG", "EC": "ECU",
  "EE": "EST", "EG": "EGY", "ER": "ERI", "ES": "ESP", "ET": "ETH",
  "FI": "FIN", "FJ": "FIJ", "FR": "FRA", "GA": "GAB", "GB": "GBR",
  "GD": "GRN", "GE": "GEO", "GH": "GHA", "GM": "GAM", "GN": "GUI",
  "GQ": "GEQ", "GR": "GRE", "GT": "GUA", "GW": "GBS", "GY": "GUY",
  "HN": "HON", "HR": "CRO", "HT": "HAI", "HU": "HUN", "ID": "INA",
  "IE": "IRL", "IL": "ISR", "IN": "IND", "IQ": "IRQ", "IR": "IRI",
  "IS": "ISL", "IT": "ITA", "JM": "JAM", "JO": "JOR", "JP": "JPN",
  "KE": "KEN", "KG": "KGZ", "KH": "CAM", "KI": "KIR", "KM": "COM",
  "KN": "SKN", "KP": "PRK", "KR": "KOR", "KW": "KUW", "KZ": "KAZ",
  "LA": "LAO", "LB": "LBN", "LC": "LCA", "LI": "LIE", "LK": "SRI",
  "LR": "LBR", "LS": "LES", "LT": "LTU", "LU": "LUX", "LV": "LAT",
  "LY": "LBA", "MA": "MAR", "MC": "MON", "MD": "MDA", "ME": "MNE",
  "MG": "MAD", "MH": "MHL", "MK": "MKD", "ML": "MLI", "MM": "MYA",
  "MN": "MGL", "MR": "MTN", "MT": "MLT", "MU": "MRI", "MV": "MDV",
  "MW": "MAW", "MX": "MEX", "MY": "MAS", "MZ": "MOZ", "NA": "NAM",
  "NE": "NIG", "NG": "NGR", "NI": "NCA", "NL": "NED", "NO": "NOR",
  "NP": "NEP", "NR": "NRU", "NZ": "NZL", "OM": "OMA", "PA": "PAN",
  "PE": "PER", "PG": "PNG", "PH": "PHI", "PK": "PAK", "PL": "POL",
  "PT": "POR", "PW": "PLW", "PY": "PAR", "QA": "QAT", "RO": "ROU",
  "RS": "SRB", "RU": "RUS", "RW": "RWA", "SA": "KSA", "SB": "SOL",
  "SC": "SEY", "SD": "SUD", "SE": "SWE", "SG": "SGP", "SI": "SLO",
  "SK": "SVK", "SL": "SLE", "SM": "SMR", "SN": "SEN", "SO": "SOM",
  "SR": "SUR", "SS": "SSD", "ST": "STP", "SV": "ESA", "SY": "SYR",
  "SZ": "SWZ", "TD": "CHA", "TG": "TOG", "TH": "THA", "TJ": "TJK",
  "TL": "TLS", "TM": "TKM", "TN": "TUN", "TO": "TGA", "TR": "TUR",
  "TT": "TTO", "TV": "TUV", "TZ": "TAN", "UA": "UKR", "UG": "UGA",
  "US": "USA", "UY": "URU", "UZ": "UZB", "VC": "VIN", "VE": "VEN",
  "VN": "VIE", "VU": "VAN", "WS": "SAM", "XK": "KOS", "YE": "YEM",
  "ZA": "RSA", "ZM": "ZAM", "ZW": "ZIM",
};
