export const LA28_SPORTS = [
  "Aquatics",
  "Archery",
  "Athletics",
  "Badminton",
  "Basketball",
  "Boxing",
  "Breaking",
  "Canoe",
  "Cricket (T20)",
  "Cycling",
  "Equestrian",
  "Fencing",
  "Flag Football",
  "Football",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hockey",
  "Judo",
  "Lacrosse",
  "Modern Pentathlon",
  "Rowing",
  "Rugby Sevens",
  "Sailing",
  "Shooting",
  "Skateboarding",
  "Sport Climbing",
  "Squash",
  "Surfing",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Triathlon",
  "Volleyball",
  "Weightlifting",
  "Wrestling",
] as const;

export type LA28Sport = typeof LA28_SPORTS[number];
