[build]
builder = "nixpacks"
installCommand = "bun install"

[deploy]
startCommand = "bun run db:migrate && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
